-- ✅ only insert if PRODUCT table is empty
INSERT INTO PRODUCT
(GTIN, BRAND_NAME, LINE_NAME, CATEGORY_CODE, DEFAULT_IMAGE_URL,
 IS_VERIFIED, ORIGIN_COUNTRY, LAST_SOURCED_AT, CREATED_AT, UPDATED_AT)
SELECT
    '8801234567890', 'TestBrand', 'Signature Line', 'COSMETICS',
    'https://via.placeholder.com/300', TRUE, 'KR', NOW(), NOW(), NOW()
FROM DUAL
WHERE (SELECT COUNT(*) FROM PRODUCT) = 0;

SET @pid := (SELECT PRODUCT_ID FROM PRODUCT WHERE GTIN = '8801234567890');

INSERT INTO PRODUCT_LOCALE
(PRODUCT_ID, LANG, PRODUCT_NAME, DESCRIPTION_TEXT, IS_REVIEWED, CREATED_AT, UPDATED_AT)
SELECT
    @pid, 'EN', 'Test Product EN', 'English description for the test product.', TRUE, NOW(), NOW()
FROM DUAL
WHERE (SELECT COUNT(*) FROM PRODUCT_LOCALE) = 0;

INSERT INTO PRODUCT_LOCALE
(PRODUCT_ID, LANG, PRODUCT_NAME, DESCRIPTION_TEXT, IS_REVIEWED, CREATED_AT, UPDATED_AT)
SELECT
    @pid, 'KO', '테스트 상품', '테스트용 상품의 한글 설명입니다.', TRUE, NOW(), NOW()
FROM DUAL
WHERE (SELECT COUNT(*) FROM PRODUCT_LOCALE) = 0;
